# Generated by Django 4.2.7 on 2024-02-12 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 14, 15, 46, 603715), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 12, 14, 15, 46, 603715), null=True),
        ),
        migrations.AlterField(
            model_name='loai',
            name='loai',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
