# Generated by Django 4.2.7 on 2024-02-12 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_brand_brand_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 14, 24, 34, 676992), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 12, 14, 24, 34, 676992), null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
